name: Benchmark with Bencher using hyperfine

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  benchmark_with_bencher:
    name: Continuous Benchmarking with Bencher
    runs-on: ubuntu-latest
    env:
      BENCHER_PROJECT: rust-bpmn-analyzer
      BENCHER_TESTBED: ubuntu-latest
      BENCHER_ADAPTER: shell
    steps:
      - name: Install hyperfine
        run: sudo apt-get install hyperfine
      - uses: actions/checkout@v4
      - name: Build APP
        run: cargo build --release
      - name: Debug
        run: ls
      - uses: bencherdev/bencher@main
      - name: Track Benchmarks with Bencher using hyperfine
        run: |
          bencher run \
          --file results.json \
          --branch "$GITHUB_REF_NAME" \
          --token "${{ secrets.BENCHER_API_TOKEN }}" \
          --err \
          "hyperfine -L bpmnModel benchmark_input/p10x01.bpmn,benchmark_input/p15x01.bpmn,benchmark_input/p17x01.bpmn "/target/release/bpmnanalyzer -f ./{bpmnModel} -p safeness,option-to-complete,proper-completion,no-dead-activities" --export-json results.json"