name: Benchmark with Bencher using hyperfine

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  benchmark_with_bencher:
    name: Continuous Benchmarking with Bencher
    runs-on: ubuntu-latest
    env:
      BENCHER_PROJECT: rust-bpmn-analyzer
      BENCHER_TESTBED: ubuntu-latest
      BENCHER_ADAPTER: json
    steps:
      - uses: actions/checkout@v4
      - uses: bencherdev/bencher@main
      - name: Track Benchmarks with Bencher using hyperfine
        run: |
          bencher run \
          --file results.json \
          --branch "$GITHUB_REF_NAME" \
          --token "${{ secrets.BENCHER_API_TOKEN }}" \
          --err \
          "hyperfine --export-json results.json 'sleep 0.1'"