name: Rust compile, lint & test CLI

on:
  workflow_dispatch:
  push:
    paths:
    - cli/**
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cli

    steps:
      - uses: actions/checkout@v5
      - name: Format
        run: cargo fmt --check
      - name: Lint
        run: cargo clippy -- -Dwarnings
      - name: Build
        run: cargo build
      - name: Run tests
        run: cargo test -- --show-output
