name: Rust compile, lint & test

on:
  workflow_dispatch:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build
      - name: Format
        run: cargo fmt --check
      - name: Lint
        run: cargo clippy -- -Dwarnings
      - name: Run tests
        run: cargo test -- --show-output
